### ISSUE TITLE
When using `clone: false` watchers are not triggered with correct entities

### ISSUE THREAD

**Issue by powerpaul17** [blinkdb-js/blinkdb#23] opened 2023-07-17 07:28 UTC
Hello,

I have a watcher on a table and the db is initialized with `clone: false`. If I, for example, `upsert` an entity, the callback of the watcher is called without the changed entity. It works if `clone` is set to `true` (which is the default).

**Comment by froehlichA** [comment] 2023-07-22 10:29
Sorry, can't reproduce your issue :/ Does your setup differ in any significant way from the testcase below? It passes for me.
```ts
let users: User[];
let userTable: Table<User, "id">;
let fn: jest.Mock<void, [User[]]>;

describe("without clone", () => {
  beforeEach(async () => {
    users = generateRandomUsers();
    const db = createDB({ clone: false });
    userTable = createTable<User>(db, "users")();
    await insertMany(userTable, users);

    fn = jest.fn<void, [User[]]>();
  });

  it("should trigger watch if a matching entity is inserted (#23)", async () => {
    await watch(userTable, { where: { name: { in: ["Alice", "Eve"] } } }, fn);
    const eve: User = { id: "300", name: "Eve", age: 5 };
    await upsert(userTable, eve);

    expect(fn.mock.calls.length).toBe(2);
    expect(fn.mock.calls[1][0].sort(sortById)).toStrictEqual(
      [...users.filter(u => u.name === "Alice" || u.name === "Eve"), eve].sort(sortById)
    );
  });
});
```

**Comment by powerpaul17** [comment] 2023-09-25 19:25
Ok, I figured out the root of the problem. If I change a property of an object while not using `clone` and the upsert the object, the watcher does not return it as changed since the object is the same in the table already.. :sweat_smile:

**Comment by froehlichA** [comment] 2023-10-08 08:51
**Modifying objects returned from the DB if you're using `clone: false` will almost certainly result in bugs.** Afaik I can't really prevent such modifications (apart from systems like change tracking which would require additional overhead). `clone: false` gives you a performance "boost" by not having to clone returned objects, but almost requires you to uses immutable objects. 

If you have code that changes properties like this:
```ts
const user = await one(userTable, { id: "300" });
user.name = "Eve";
await upsert(userTable, user);
```

consider rewriting it to look like this:
```ts
const user = await one(userTable, { id: "300" });
await upsert(userTable, { ...user, name: "Eve" });
```

**Comment by froehlichA** [comment] 2023-10-17 22:34
I know that running into bugs like this is surprising, but this is the price you have to pay for an API that works without clone :/
Since I don't expect there to be a follow up, I'm closing this issue.

**Closed by froehlichA** 2023-10-17 22:34 UTC

**Comment by powerpaul17** [comment] 2023-10-18 07:06
Since it doesn't really make sense to use it with `clone: false` anyway, maybe the option should be removed completely?
